# netlify.toml
[build]
  publish = "frontend"                # folder with your index.html
  functions = "netlify/functions"     # folder where Netlify looks for serverless functions

# optional: redirect everything under .netlify/functions to lambda endpoint (not required usually)
# [[redirects]]
#   from = "/.netlify/functions/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
